# gemini_helper.py
# This file handles everything related to talking to Google's Gemini AI model.

# os lets us read environment variables (like our secret API key) from the system.
import os

# load_dotenv reads the .env file and loads its contents into the environment,
# so we can access variables like GEMINI_API_KEY using os.getenv().
from dotenv import load_dotenv

# This is Google's official library to interact with the Gemini API.
import google.generativeai as genai


# Step 1: Load the variables from our .env file into memory.
# Without this line, os.getenv() would not find GEMINI_API_KEY.
load_dotenv()

# Step 2: Read the API key from the environment.
# os.getenv("GEMINI_API_KEY") looks for a variable named GEMINI_API_KEY
# which we defined earlier inside our .env file.
api_key = os.getenv("GEMINI_API_KEY")

# Step 3: Configure the Gemini library with our API key.
# This tells Google's library: "use this key to authenticate all my requests."
genai.configure(api_key=api_key)

# Step 4: Create the model object we will reuse across all functions.
# "gemini-1.5-flash" is a fast, low-cost Gemini model good for beginner projects.
model = genai.GenerativeModel("gemini-1.5-flash")


def generate_summary(pdf_text):
    """
    Takes the full PDF text and asks Gemini to summarize it.

    Parameters:
        pdf_text (str): The full extracted text from the PDF.

    Returns:
        str: A short summary generated by Gemini.
    """

    # We build a "prompt" — the instruction we send to the AI model.
    # Being specific in prompts gives better results.
    prompt = f"""
    Summarize the following document in simple, easy-to-understand English.
    Keep the summary short (around 150-200 words) and use bullet points
    for the main ideas.

    Document:
    {pdf_text}
    """

    # We send the prompt to Gemini using .generate_content()
    # This actually makes the API call over the internet.
    response = model.generate_content(prompt)

    # The response object contains the AI's reply inside response.text
    return response.text


def answer_question(pdf_text, question):
    """
    Takes the PDF text and a user's question, and asks Gemini to answer
    the question using ONLY the information from the PDF.

    Parameters:
        pdf_text (str): The full extracted text from the PDF.
        question (str): The question typed by the user.

    Returns:
        str: Gemini's answer to the question.
    """

    # We instruct the model to answer strictly based on the document,
    # so it doesn't make up information (this reduces "hallucination").
    prompt = f"""
    You are a helpful assistant. Answer the question using ONLY the
    information found in the document below. If the answer is not
    present in the document, say "I could not find this in the document."

    Document:
    {pdf_text}

    Question:
    {question}
    """

    response = model.generate_content(prompt)
    return response.text


def explain_simply(pdf_text, topic):
    """
    Takes a difficult topic mentioned in the PDF and asks Gemini to
    explain it in very simple English, like explaining to a beginner.

    Parameters:
        pdf_text (str): The full extracted text from the PDF.
        topic (str): The specific topic/question the user wants simplified.

    Returns:
        str: A simplified explanation from Gemini.
    """

    prompt = f"""
    Based on the document below, explain the topic "{topic}" in very
    simple English, as if explaining to a complete beginner with no
    prior knowledge. Use short sentences and simple everyday words.
    Use an analogy or example if it helps.

    Document:
    {pdf_text}
    """

    response = model.generate_content(prompt)
    return response.text
